
###get all users
GET http://localhost:4000/user-router/users

###create user

POST  http://localhost:4000/user-router/users
Content-Type: application/json

{    "name":"Harish",
    "email":"harishh@gmail.com",
    "dob":"2005-04-17",
    "mobileno":"7993604056"
}

###read user by id
GET http://localhost:4000/user-router/users/69a68439373e1b8b6a6bf53e


###soft delete user by id
DELETE  http://localhost:4000/user-router/users/69a681f0c7bd73d487a39a8d

###activate user
PATCH http://localhost:4000/user-router/users/69a681f0c7bd73d487a39a8d